# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rNYaQEIJt9s1d2woD_BmDwhQHsSNLwZX
"""

# app.py
# ============================================================
# ROMANTIC STREAMLIT LOVE STORY — Premium / Cinematic UI
# ============================================================
# ✅ Semua teks romantis ada di variabel (mudah diedit di atas).
# ✅ Gallery foto pakai folder lokal: ./images/photo1.jpg dst.
# ✅ Section collapsible (st.expander) + clickable chapter nav (anchor).
# ✅ Soft palette: cream / soft pink / warm beige / muted gold.
# ✅ Elegant typography + card layout + soft dividers + “reveal” transitions.
# ✅ Bonus: background gradient + romantic footer + optional music (commented).
# ============================================================

from __future__ import annotations

import html as _html
import re
import time
from pathlib import Path
from typing import Dict, List

import streamlit as st
from PIL import Image


# ============================================================
# 1) EDITABLE TEXT VARIABLES (EDIT DI SINI — layout jangan diubah)
# ============================================================

PAGE_TITLE = "A Love Story 🌙"
PAGE_ICON = "💗"

# --- HERO / WELCOME ---
hero_tagline = "A DIGITAL LOVE LETTER"
hero_headline = "To My Favorite Person"
hero_subheadline = "A small, soft place on the internet… made just for you."
hero_micro_poem = """
In the quiet between heartbeats,
I find you again—always.
"""

# --- GRATITUDE ---
gratitude_text = """
I want to start with **thank you**.

Thank you for your patience, your warmth, and the way you show up—especially when it would be easier not to.
Thank you for the little things you do that you probably don’t even realize are extraordinary.

- Thank you for your honesty.
- Thank you for your gentleness.
- Thank you for choosing love, even on difficult days.

If I don’t say it enough: I see you, and I’m grateful for you.
"""

gratitude_side_title = "A soft truth"
gratitude_side_text = """
You’ve made my world calmer.
You’ve made my heart braver.
And I never want to take that for granted.
"""

# --- APOLOGY ---
apology_text = """
I’m sorry for the moments I fell short.

Sorry for the times my words didn’t reflect my feelings,
or when I didn’t listen the way you deserved to be listened to.

I’m not asking for perfection from us—only for **growth**, and for the courage to keep choosing each other.
I want to do better, not in big dramatic promises… but in the everyday ways that matter most.
"""

apology_side_title = "What I’m learning"
apology_side_text = """
Love is not just how we feel.
It’s how we speak.
How we pause.
How we repair.
How we return.
"""

# --- LOVE & DEVOTION ---
love_text = """
I love you—deeply, quietly, completely.

I love the way you think.
I love the way you care.
I love the way your presence can make a hard day feel survivable.

When I picture “home,” I don’t picture a place.
I picture **you**.

And if loving you is a choice, then it’s the easiest one I’ll ever make.
"""

love_side_title = "My devotion"
love_side_text = """
I’ll keep choosing you:

- when it’s easy
- when it’s hard
- when it’s ordinary
- when it’s beautiful

I’m here. I’m staying.
"""

# --- FUTURE & MARRIAGE ---
future_text = """
I don’t just want a future *near* you.
I want a future **with** you.

A life built from simple things:
morning light, shared meals, inside jokes, honest conversations,
and hands reaching for each other without thinking.

If marriage is a promise, then I want mine to sound like this:
*I will protect our love. I will nurture our peace. I will keep showing up.*
"""

future_side_title = "A gentle dream"
future_side_text = """
Someday, I want to look at you and know:

We did it the right way.
With kindness.
With intention.
With love that kept becoming more.
"""

# --- MEMORIES ---
memories_intro_text = """
Here are a few memories—little frames of time I never want to forget.

(Replace the images in the /images folder to make this gallery yours.)
"""

# --- VALENTINE’S & FUTURE DAYS ---
valentines_text = """
Not just Valentine’s Day—**every** day.

Let’s celebrate the small days too:
the random Tuesdays, the quiet nights, the “I’m proud of you” moments,
the “I’m here” moments.

And for the future days—birthdays, anniversaries, new chapters—
I want us to meet them hand-in-hand, with love that feels safe and alive.
"""

valentines_side_title = "A simple vow"
valentines_side_text = """
I’ll love you loudly in the ways that matter,
and softly in the ways you need.

Happy Valentine’s—today, and all the days ahead.
"""

# --- FOOTER ---
closing_footer_text = "Built with love, for you. 💗"


# ============================================================
# 2) PHOTO GALLERY SETTINGS (EDIT NAMA FILE + CAPTION DI SINI)
# ============================================================

# Letakkan foto di folder: ./images/
# Contoh: ./images/photo1.jpg, ./images/photo2.jpg
PHOTO_ITEMS: List[Dict[str, str]] = [
    {"file": "photo1.jpg", "caption": "A moment I still replay in my mind."},
    {"file": "photo2.jpg", "caption": "Where everything felt a little softer."},
    {"file": "photo3.jpg", "caption": "Proof that the ordinary can be magical."},
    {"file": "photo4.jpg", "caption": "One of my favorite days with you."},
    {"file": "photo5.jpg", "caption": "A memory that feels like warm light."},
    {"file": "photo6.jpg", "caption": "Us—exactly as we are."},
]

GALLERY_COLUMNS = 3  # ubah jadi 2 atau 4 kalau mau


# ============================================================
# 3) STREAMLIT CONFIG
# ============================================================

st.set_page_config(
    page_title=PAGE_TITLE,
    page_icon=PAGE_ICON,
    layout="wide",
    initial_sidebar_state="collapsed",
)

APP_DIR = Path(__file__).resolve().parent
IMAGES_DIR = APP_DIR / "images"


# ============================================================
# 4) PREMIUM ROMANTIC CSS
# ============================================================

def inject_css() -> None:
    st.markdown(
        """
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;600;700&family=Inter:wght@300;400;500;600&display=swap');

:root{
  --cream: #FFF7EF;
  --soft-pink: #F7D9E3;
  --warm-beige: #F3E7D8;
  --muted-gold: #C7A65B;
  --ink: #2B2B2B;
  --ink-soft: rgba(43,43,43,0.78);
  --glass: rgba(255,255,255,0.52);
  --glass-strong: rgba(255,255,255,0.66);
  --stroke: rgba(199,166,91,0.28);
  --shadow: 0 16px 60px rgba(0,0,0,0.08);
}

/* Romantic gradient background */
.stApp{
  background:
    radial-gradient(1200px 800px at 15% 10%, rgba(247,217,227,0.60) 0%, rgba(247,217,227,0.00) 60%),
    radial-gradient(900px 700px at 85% 20%, rgba(243,231,216,0.85) 0%, rgba(243,231,216,0.00) 55%),
    linear-gradient(135deg, var(--cream) 0%, var(--soft-pink) 35%, var(--warm-beige) 75%, var(--cream) 100%);
  background-attachment: fixed;
}

section.main .block-container{
  max-width: 1120px;
  padding-top: 2.2rem;
  padding-bottom: 3rem;
}

/* Hide Streamlit chrome */
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
header {visibility: hidden;}

/* Typography */
html, body, [class*="css"]{
  font-family: Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
  color: var(--ink);
}
h1, h2, h3, h4{
  font-family: "Playfair Display", Georgia, serif;
  letter-spacing: 0.2px;
}
p, li{
  color: var(--ink-soft);
  line-height: 1.85;
  font-size: 1.05rem;
}

/* Hero */
.hero{
  background: linear-gradient(180deg, var(--glass-strong), rgba(255,255,255,0.40));
  border: 1px solid var(--stroke);
  box-shadow: var(--shadow);
  border-radius: 28px;
  padding: 2.1rem 2.2rem;
  position: relative;
  overflow: hidden;
  animation: fadeUp .60s ease both;
}
.hero::before{
  content:"";
  position:absolute;
  inset:-2px;
  background:
    radial-gradient(540px 260px at 20% 30%, rgba(199,166,91,0.18), transparent 60%),
    radial-gradient(440px 240px at 80% 20%, rgba(247,217,227,0.28), transparent 60%);
  pointer-events:none;
}
.hero .tag{
  font-size:1.00rem;
  letter-spacing:.10em;
  color: rgba(43,43,43,0.60);
}
.hero h1{
  font-size: 3.05rem;
  margin: 0.25rem 0 0.25rem 0;
}
.hero .sub{
  font-size: 1.15rem;
  margin-top: 0.15rem;
  color: var(--ink-soft);
}
.hero .micro{
  margin-top: 1.2rem;
  padding-top: 1rem;
  border-top: 1px solid rgba(199,166,91,0.22);
  font-style: italic;
  color: rgba(43,43,43,0.72);
}

/* Soft divider */
.soft-divider{
  height: 1px;
  background: linear-gradient(90deg, transparent, rgba(199,166,91,0.55), transparent);
  margin: 1.4rem 0;
  opacity: 0.75;
}

/* Chapter nav pills */
.navbar{
  display:flex;
  flex-wrap: wrap;
  gap: .55rem;
  margin: 1.0rem 0 1.25rem 0;
}
.nav-pill{
  display:inline-flex;
  align-items:center;
  gap:.45rem;
  padding: .55rem .85rem;
  border-radius: 999px;
  background: rgba(255,255,255,0.55);
  border: 1px solid rgba(199,166,91,0.22);
  box-shadow: 0 10px 30px rgba(0,0,0,0.05);
  text-decoration:none;
  font-size: .95rem;
  color: rgba(43,43,43,0.88);
  transition: transform .18s ease, background .18s ease, border .18s ease;
}
.nav-pill:hover{
  transform: translateY(-2px);
  background: rgba(255,255,255,0.70);
  border: 1px solid rgba(199,166,91,0.32);
}

/* Expanders premium look */
div[data-testid="stExpander"]{
  border-radius: 22px;
  border: 1px solid rgba(199,166,91,0.22);
  background: rgba(255,255,255,0.35);
  box-shadow: 0 12px 44px rgba(0,0,0,0.06);
  overflow: hidden;
}
div[data-testid="stExpander"] summary{
  padding: 1rem 1.1rem;
  font-family: "Playfair Display", Georgia, serif;
  font-size: 1.2rem;
  color: rgba(43,43,43,0.90);
}
div[data-testid="stExpander"] summary:hover{
  background: rgba(255,255,255,0.25);
}

/* Cards */
.paper, .aside{
  border-radius: 22px;
  padding: 1.25rem 1.35rem;
  border: 1px solid rgba(199,166,91,0.22);
  box-shadow: 0 14px 50px rgba(0,0,0,0.06);
  backdrop-filter: blur(10px);
  -webkit-backdrop-filter: blur(10px);
  animation: fadeUp .55s ease both;
}
.paper{ background: rgba(255,255,255,0.62); }
.aside{ background: linear-gradient(180deg, rgba(247,217,227,0.52), rgba(255,255,255,0.55)); }
.card-title{
  margin: 0 0 .55rem 0;
  font-size: 1.35rem;
}
.soft-hint{
  text-align:center;
  margin-top: .75rem;
  color: rgba(43,43,43,0.60);
  font-size: .98rem;
}

/* Buttons */
.stButton > button{
  border-radius: 999px !important;
  padding: .6rem 1.05rem !important;
  border: 1px solid rgba(199,166,91,0.26) !important;
  background: rgba(255,255,255,0.68) !important;
  transition: transform .18s ease, background .18s ease;
}
.stButton > button:hover{
  transform: translateY(-1px);
  background: rgba(255,255,255,0.82) !important;
}

/* Images */
div[data-testid="stImage"] img{
  border-radius: 18px;
  border: 1px solid rgba(199,166,91,0.22);
  box-shadow: 0 16px 60px rgba(0,0,0,0.10);
}
.img-caption{
  margin-top: .45rem;
  font-size: .95rem;
  color: rgba(43,43,43,0.68);
  font-style: italic;
}
.missing-photo{
  border-radius: 18px;
  padding: 1.1rem 1rem;
  border: 1px dashed rgba(199,166,91,0.45);
  background: rgba(255,255,255,0.40);
  color: rgba(43,43,43,0.70);
}

/* Footer */
.romantic-footer{
  margin-top: 2.2rem;
  padding: 1.2rem 1.2rem;
  text-align: center;
  border-radius: 18px;
  background: rgba(255,255,255,0.45);
  border: 1px solid rgba(199,166,91,0.18);
  color: rgba(43,43,43,0.70);
}

/* Animations */
@keyframes fadeUp{
  from {opacity: 0; transform: translateY(10px);}
  to   {opacity: 1; transform: translateY(0);}
}
</style>
        """,
        unsafe_allow_html=True,
    )


# ============================================================
# 5) HELPERS — text formatting + reveal interactions
# ============================================================

def _apply_light_formatting(escaped: str) -> str:
    """
    Convert a small subset of markdown-like markers into HTML (input is already escaped):
      **bold**   -> <strong>
      *italic*   -> <em>
    """
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)", r"<em>\1</em>", escaped)
    return escaped


def text_to_html_blocks(text: str) -> str:
    """
    Turns simple editable text into readable HTML:
    - Blank lines -> paragraph breaks
    - Lines starting with "- " or "• " -> bullet lists
    - Supports **bold** and *italic*
    - Escapes HTML for safety
    """
    raw = (text or "").strip()
    if not raw:
        return "<p></p>"

    lines = raw.splitlines()
    out: List[str] = []
    para_buf: List[str] = []
    list_buf: List[str] = []

    def flush_paragraph() -> None:
        nonlocal para_buf
        if para_buf:
            content = _html.escape("\n".join(para_buf)).replace("\n", "<br>")
            content = _apply_light_formatting(content)
            out.append(f"<p>{content}</p>")
            para_buf = []

    def flush_list() -> None:
        nonlocal list_buf
        if list_buf:
            items = []
            for item in list_buf:
                item_esc = _apply_light_formatting(_html.escape(item))
                items.append(f"<li>{item_esc}</li>")
            out.append("<ul>" + "".join(items) + "</ul>")
            list_buf = []

    for line in lines:
        stripped = line.strip()

        if stripped == "":
            flush_paragraph()
            flush_list()
            continue

        is_bullet = stripped.startswith("- ") or stripped.startswith("• ")
        if is_bullet:
            flush_paragraph()
            list_buf.append(stripped[2:].strip())
        else:
            flush_list()
            para_buf.append(stripped)

    flush_paragraph()
    flush_list()
    return "".join(out)


@st.cache_data(show_spinner=False)
def load_image(path: Path) -> Image.Image:
    return Image.open(path)


def revealable_text_card(key: str, text: str, button_label: str) -> None:
    """
    “Animation-like” transition:
    - Start as a reveal button
    - On click, show a short spinner delay, then reveal the content
    """
    if key not in st.session_state:
        st.session_state[key] = False

    if not st.session_state[key]:
        c1, c2, c3 = st.columns([0.25, 0.5, 0.25], gap="small")
        with c2:
            pressed = st.button(button_label, key=f"{key}_btn")
        st.markdown('<div class="soft-hint">Tap to unfold the words—slowly, softly.</div>', unsafe_allow_html=True)

        if pressed:
            with st.spinner("Unfolding…"):
                time.sleep(0.35)
            st.session_state[key] = True
            if hasattr(st, "toast"):
                st.toast("💗", icon="✨")

    if st.session_state[key]:
        st.markdown(f'<div class="paper">{text_to_html_blocks(text)}</div>', unsafe_allow_html=True)


def side_note_card(title: str, text: str) -> None:
    st.markdown(
        f"""
        <div class="aside">
          <div class="card-title">{_html.escape(title)}</div>
          {text_to_html_blocks(text)}
        </div>
        """,
        unsafe_allow_html=True,
    )


def chapter_nav() -> None:
    pills = [
        ("🌸 Welcome", "welcome"),
        ("💌 Gratitude", "gratitude"),
        ("🤍 Apology", "apology"),
        ("🌹 Love & Devotion", "love"),
        ("💍 Future & Marriage", "future"),
        ("📸 Our Memories", "memories"),
        ("✨ Valentine’s & Future Days", "valentines"),
    ]
    links = "\n".join([f'<a class="nav-pill" href="#{anchor}">{label}</a>' for (label, anchor) in pills])
    st.markdown(f'<div class="navbar">{links}</div>', unsafe_allow_html=True)


# ============================================================
# 6) RENDER APP
# ============================================================

inject_css()

# Small “first-open” delight
if "first_open" not in st.session_state:
    st.session_state["first_open"] = True
    if hasattr(st, "toast"):
        st.toast("A little love story is ready ✨", icon="💗")

# --- HERO / WELCOME ---
st.markdown('<a id="welcome"></a>', unsafe_allow_html=True)
st.markdown(
    f"""
    <div class="hero">
      <div class="tag">{_html.escape(hero_tagline)}</div>
      <h1>{_html.escape(hero_headline)} <span style="color: rgba(199,166,91,0.95);">✦</span></h1>
      <div class="sub">{_html.escape(hero_subheadline)}</div>
      <div class="micro">{text_to_html_blocks(hero_micro_poem)}</div>
    </div>
    """,
    unsafe_allow_html=True,
)

chapter_nav()
st.markdown('<div class="soft-divider"></div>', unsafe_allow_html=True)

# --- GRATITUDE ---
st.markdown('<a id="gratitude"></a>', unsafe_allow_html=True)
with st.expander("💌 Gratitude Section", expanded=False):
    left, right = st.columns([1.35, 1], gap="large")
    with left:
        revealable_text_card("reveal_gratitude", gratitude_text, "Reveal gratitude 💌")
    with right:
        side_note_card(gratitude_side_title, gratitude_side_text)

st.markdown('<div class="soft-divider"></div>', unsafe_allow_html=True)

# --- APOLOGY ---
st.markdown('<a id="apology"></a>', unsafe_allow_html=True)
with st.expander("🤍 Apology Section", expanded=False):
    left, right = st.columns([1.35, 1], gap="large")
    with left:
        revealable_text_card("reveal_apology", apology_text, "Reveal apology 🤍")
    with right:
        side_note_card(apology_side_title, apology_side_text)

st.markdown('<div class="soft-divider"></div>', unsafe_allow_html=True)

# --- LOVE & DEVOTION ---
st.markdown('<a id="love"></a>', unsafe_allow_html=True)
with st.expander("🌹 Love & Devotion Section", expanded=False):
    left, right = st.columns([1.35, 1], gap="large")
    with left:
        revealable_text_card("reveal_love", love_text, "Reveal love 🌹")
    with right:
        side_note_card(love_side_title, love_side_text)

st.markdown('<div class="soft-divider"></div>', unsafe_allow_html=True)

# --- FUTURE & MARRIAGE ---
st.markdown('<a id="future"></a>', unsafe_allow_html=True)
with st.expander("💍 Future & Marriage Section", expanded=False):
    left, right = st.columns([1.35, 1], gap="large")
    with left:
        revealable_text_card("reveal_future", future_text, "Reveal the future 💍")
    with right:
        side_note_card(future_side_title, future_side_text)

st.markdown('<div class="soft-divider"></div>', unsafe_allow_html=True)

# --- MEMORIES / PHOTO GALLERY ---
st.markdown('<a id="memories"></a>', unsafe_allow_html=True)
with st.expander("📸 Our Memories (Photo Gallery)", expanded=False):
    st.markdown(f'<div class="paper">{text_to_html_blocks(memories_intro_text)}</div>', unsafe_allow_html=True)

    cols = st.columns(GALLERY_COLUMNS, gap="medium")
    for i, item in enumerate(PHOTO_ITEMS):
        with cols[i % GALLERY_COLUMNS]:
            img_path = IMAGES_DIR / item["file"]
            caption = item.get("caption", "").strip()

            if img_path.exists():
                try:
                    img = load_image(img_path)
                    st.image(img, use_container_width=True)
                    if caption:
                        st.markdown(f'<div class="img-caption">{_html.escape(caption)}</div>', unsafe_allow_html=True)
                except Exception:
                    st.markdown(
                        f'<div class="missing-photo">Could not load <strong>{_html.escape(item["file"])}</strong>.</div>',
                        unsafe_allow_html=True,
                    )
            else:
                st.markdown(
                    f"""
                    <div class="missing-photo">
                      <strong>Missing photo:</strong> {_html.escape(item["file"])}<br>
                      Put it inside <code>/images</code> or update PHOTO_ITEMS at the top.
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

st.markdown('<div class="soft-divider"></div>', unsafe_allow_html=True)

# --- VALENTINE’S & FUTURE DAYS ---
st.markdown('<a id="valentines"></a>', unsafe_allow_html=True)
with st.expander("✨ Valentine’s & Future Days Section", expanded=False):
    left, right = st.columns([1.35, 1], gap="large")
    with left:
        revealable_text_card("reveal_valentines", valentines_text, "Reveal Valentine’s & future days ✨")
    with right:
        side_note_card(valentines_side_title, valentines_side_text)

# --- OPTIONAL BACKGROUND MUSIC (COMMENTED) ---
# Tips:
# 1) Buat folder: ./assets
# 2) Taruh file: ./assets/music.mp3
# 3) Uncomment block ini untuk mengaktifkan audio.
#
# ASSETS_DIR = APP_DIR / "assets"
# music_path = ASSETS_DIR / "music.mp3"
# with st.sidebar:
#     st.markdown("### 🎵 Background music")
#     if music_path.exists():
#         st.audio(music_path.read_bytes(), format="audio/mp3")
#     else:
#         st.caption("Add an MP3 at ./assets/music.mp3 to enable music.")

# --- FOOTER ---
st.markdown(
    f"""
    <div class="romantic-footer">
      {_html.escape(closing_footer_text)}
    </div>
    """,
    unsafe_allow_html=True,
)

# ============================================================
# INSTRUCTIONS (DI BAWAH INI BIAR GAMPANG)
# ============================================================
#
# ✅ Cara run:
#   pip install streamlit pillow
#   streamlit run app.py
#
# ✅ Cara edit teks:
#   Edit variabel di bagian paling atas file ini, misalnya:
#     gratitude_text = """ ... """
#     love_text = """ ... """
#   Kamu bisa pakai:
#     **bold**, *italic*, dan bullet list dengan "- "
#
# ✅ Cara ganti foto:
#   1) Buat folder "images" sejajar dengan app.py
#   2) Masukkan foto:
#        ./images/photo1.jpg
#        ./images/photo2.jpg
#   3) Pilih:
#      - Replace file dengan nama yang sama, atau
#      - Ubah list PHOTO_ITEMS (file + caption) di atas
#
# ✅ Deploy (GitHub → Streamlit Cloud):
#   - Push project ke GitHub (app.py, requirements.txt, folder images/)
#   - Buka https://share.streamlit.io → New app → pilih repo → main file: app.py → Deploy
#
# ============================================================